services:
  # === Staging PostgreSQL ===
  staging_db:
    image: postgres:16-alpine
    container_name: lexi_buddy_staging_db
    restart: unless-stopped
    networks:
      - staging_net
    env_file:
      - .env.staging
    volumes:
      - staging_db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432" # наружный порт для подключения к тестовой БД
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: ["postgres", "-c", "listen_addresses=*"]


  # === Staging Backend API (NestJS) ===
  staging_api:
    image: ghcr.io/j-lany/lexi-buddy-backend:develop
    container_name: lexi_buddy_staging_api
    restart: unless-stopped
    networks:
      - staging_net
    depends_on:
      staging_db:
        condition: service_healthy
    env_file:
      - .env.staging
    environment:
      NODE_ENV: staging
      PORT: 4001
    ports:
      - "4001:4001"

  # === Staging Frontend (Next.js) ===
  staging_frontend:
    image: ghcr.io/j-lany/lexi-buddy-frontend:develop
    container_name: lexi_buddy_staging_frontend
    restart: unless-stopped
    networks:
      - staging_net
    depends_on:
      staging_api:
        condition: service_started
    env_file:
      - .env.staging
    environment:
      NODE_ENV: staging
      PORT: 3001
      NEXT_PUBLIC_API_URL: http://46.16.14.86:4001
    ports:
      - "3001:3001"

  # === Staging Telegram Bot ===
  staging_bot:
    image: ghcr.io/j-lany/lexi-buddy-bot:develop
    container_name: lexi_buddy_staging_bot
    restart: unless-stopped
    networks:
      - staging_net
    depends_on:
      staging_api:
        condition: service_started
    env_file:
      - .env.staging
    environment:
      NODE_ENV: staging
    ports:
      - "8081:8080"

volumes:
  staging_db_data:

networks:
  staging_net:
